package com.supplysync.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SalesOrderSummaryResponse {

    @Schema(description = "The total count of sales orders in the specified period", example = "420")
    private Long totalOrders;

    @Schema(description = "The total revenue generated in the specified period", example = "245000.99")
    private BigDecimal totalRevenue;

    @Schema(description = "The average order value (total revenue / order count)", example = "583.33")
    private BigDecimal averageOrderValue;

    @Schema(description = "Breakdown metrics mapped by sales order status")
    private Map<String, StatusCountValue> statusBreakdown;

    @Schema(description = "The list of top products by revenue generated")
    private List<ProductRevenue> topProducts;

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class StatusCountValue {
        @Schema(description = "The count of sales orders in this status", example = "10")
        private Long count;

        @Schema(description = "The total value of sales orders in this status", example = "4999.90")
        private BigDecimal value;
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class ProductRevenue {
        @Schema(description = "The database ID of the product", example = "12")
        private Long productId;

        @Schema(description = "The stock keeping unit (SKU) of the product", example = "MON-UW-34")
        private String sku;

        @Schema(description = "The name of the product", example = "Ultra-Wide Monitor 34\"")
        private String productName;

        @Schema(description = "The total revenue generated by this product", example = "59998.80")
        private BigDecimal totalRevenue;
    }
}
